# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HealthSelf' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HealthSelf

  target 'HealthSelfTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HealthSelfUITests' do
    # Pods for testing
  end
pod 'Masonry'
pod 'AFNetworking'
pod 'SDWebImage'
end
